### ISSUE TITLE
Installation script or instructions?

### ISSUE THREAD

**Issue by nixoye** [yureru/R-a-dio#1]
Not sure how far a long this project is but if it is already useable could we get an auto install script or atleast some instructions to get this running?

**Comment by yureru** [comment]
Hi @NIXOYE 
I've added the installation instructions, you can find them here: https://github.com/yureru/R-a-dio#installation
Hope they're clear enough, and thanks for opening this request.

**Comment by nixoye** [comment]
any linux client coming? cli or gui? i want to run an instance of R-a-d.io on a vps

**Comment by yureru** [comment]
> any linux client coming? cli or gui?

The biggest problem here is that Mono doesn't provide an implementation of WPF (which I use to make the UI), and I don't know if the library NAudio works with Mono too.

> i want to run an instance of R-a-d.io on a vps

Do you mean the streamer? You might wanna check the R/a/dio project: https://github.com/R-a-dio
