### ISSUE TITLE
Make an actual build

### ISSUE THREAD

**Issue by Zyst** [yureru/R-a-dio#2]
Make an actual build and put it under releases, expecting people to compile your stuff is a bit unrealistic.

**Comment by yureru** [comment]
Yeah you're right, going to learn how to actually deploy it. Thanks for the issue.

**Comment by Zyst** [comment]
https://github.com/yureru/R-a-dio/releases 0 Releases

**Comment by Zyst** [comment]
![fastone](https://cloud.githubusercontent.com/assets/3832380/20495217/be731e00-afe5-11e6-8be2-e273ba66104c.jpg)

**Comment by yureru** [comment]
![hyouka-ep20-scr3](https://cloud.githubusercontent.com/assets/1652194/20505250/3eb95aea-b011-11e6-951a-7aa7989490cc.jpg)
Installer is now under releases!
